#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine nginx
#nginx should be listed on port 80
apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' 
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
