#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow  'Nginx HTTP'

# code to redirect a specific endpoint (eg: redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4)
echo "Hello World!" > /var/www/html/index.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# restart the server
sudo service nginx restart
