#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx - 
apt-get -y update && apt-get -y install nginx 
mkdir -p /var/www/
echo "Holberton School" | sudo tee /var/www/index.html 
echo "Ceci n'est pas une page" | sudo tee /var/www/custom_404.html
rm -f /etc/nginx/sites-enabled/default 
echo -e "
server {
	listen 80 default_server;
	root /var/www;
	index index.html index.htm;

	location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

      	error_page 404 /custom_404.html;
	      location = /custom_404.html {
        root /var/www;
		    internal;
      	}
}" | sudo tee /etc/nginx/sites-available/www 
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/ 
sudo nginx -t && sudo service nginx restart
