#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install nginx

# Insert X-served header
echo 'http { add_header X-Served-By $hostname; }' | sudo tee -a /etc/nginx/nginx.conf
sudo systemctl restart nginx
